from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class BoutRow:
    delta: float
    outcome: int


@dataclass(frozen=True)
class SweepRow:
    q_link: float
    raw_brier: float
    raw_baseline_brier: float
    raw_brier_skill: float
    n_obs: int
    base_rate: float


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Sweep q as a post hoc link parameter on fixed Expt3 bout trajectories."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="Bout-level CSV written by expt3 --bout-output",
    )
    parser.add_argument("--q-start", type=float, default=None)
    parser.add_argument("--q-end", type=float, default=None)
    parser.add_argument("--q-step", type=float, default=None)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("files/output/Equelo/expt3_link_sweep.csv"),
        help="Output CSV path for the sweep.",
    )

    parser.add_argument(
        "--input-q400",
        type=Path,
        default=None,
        help="Bout CSV generated by expt3 with q=400.",
    )
    parser.add_argument(
        "--input-q850",
        type=Path,
        default=None,
        help="Bout CSV generated by expt3 with q=850.",
    )
    parser.add_argument(
        "--output-2x2",
        type=Path,
        default=Path("files/output/Equelo/expt3_link_2x2.csv"),
        help="Output CSV path for the 2x2 summary.",
    )
    return parser


def _q_values(start: float, end: float, step: float) -> list[float]:
    if step <= 0:
        raise ValueError(f"q-step must be positive, got {step}")
    if end < start:
        raise ValueError(f"q-end must be >= q-start, got {start}..{end}")

    values: list[float] = []
    q = start
    eps = step / 1_000_000
    while q <= end + eps:
        values.append(round(q, 10))
        q += step
    return values


def _load_bouts(path: Path) -> list[BoutRow]:
    rows: list[BoutRow] = []
    with open(path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {"delta", "outcome"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Input file missing required columns: {sorted(missing)}")

        for row in reader:
            rows.append(
                BoutRow(
                    delta=float(row["delta"]),
                    outcome=int(row["outcome"]),
                )
            )
    if not rows:
        raise ValueError(f"Input file contains no bout rows: {path}")
    return rows


def _predict_from_delta(delta: float, q_link: float) -> float:
    return 1.0 / (1.0 + 10.0 ** (-delta / q_link))


def _evaluate(bouts: list[BoutRow], q_link: float) -> SweepRow:
    n = len(bouts)
    total_wins = sum(row.outcome for row in bouts)
    base_rate = total_wins / n

    brier_sum = 0.0
    baseline_sum = 0.0

    for row in bouts:
        p = _predict_from_delta(row.delta, q_link)
        y = row.outcome
        brier_sum += (p - y) ** 2
        baseline_sum += (base_rate - y) ** 2

    raw_brier = brier_sum / n
    raw_baseline_brier = baseline_sum / n
    raw_brier_skill = (
        0.0
        if raw_baseline_brier == 0.0
        else 1.0 - (raw_brier / raw_baseline_brier)
    )

    return SweepRow(
        q_link=q_link,
        raw_brier=raw_brier,
        raw_baseline_brier=raw_baseline_brier,
        raw_brier_skill=raw_brier_skill,
        n_obs=n,
        base_rate=base_rate,
    )


def _write_sweep_csv(rows: list[SweepRow], output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "q_link",
                "raw_brier",
                "raw_baseline_brier",
                "raw_brier_skill",
                "n_obs",
                "base_rate",
            ]
        )
        for row in rows:
            writer.writerow(
                [
                    row.q_link,
                    row.raw_brier,
                    row.raw_baseline_brier,
                    row.raw_brier_skill,
                    row.n_obs,
                    row.base_rate,
                ]
            )
    return output_path


def _write_2x2_csv(rows: list[dict[str, float | int]], output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "q_sim",
                "q_link",
                "raw_brier",
                "raw_baseline_brier",
                "raw_brier_skill",
                "n_obs",
                "base_rate",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)
    return output_path


def _run_sweep(input_path: Path, q_start: float, q_end: float, q_step: float, output_path: Path) -> None:
    bouts = _load_bouts(input_path)
    q_values = _q_values(q_start, q_end, q_step)

    rows: list[SweepRow] = []
    for q_link in q_values:
        row = _evaluate(bouts, q_link)
        rows.append(row)
        print(
            f"q_link={q_link:g} "
            f"raw_brier={row.raw_brier:.6f} "
            f"raw_skill={row.raw_brier_skill:.6f}"
        )

    written = _write_sweep_csv(rows, output_path)
    best = min(rows, key=lambda r: r.raw_brier)

    print()
    print(f"Wrote {len(rows)} rows to: {written}")
    print("Best q_link by raw Brier:")
    print(f"  q_link: {best.q_link:g}")
    print(f"  raw_brier: {best.raw_brier:.6f}")
    print(f"  raw_brier_skill: {best.raw_brier_skill:.6f}")


def _run_2x2(input_q400: Path, input_q850: Path, output_path: Path) -> None:
    bouts_400 = _load_bouts(input_q400)
    bouts_850 = _load_bouts(input_q850)

    rows: list[dict[str, float | int]] = []
    for q_sim, bouts in [(400, bouts_400), (850, bouts_850)]:
        for q_link in (400, 850):
            result = _evaluate(bouts, q_link)
            rows.append(
                {
                    "q_sim": q_sim,
                    "q_link": q_link,
                    "raw_brier": result.raw_brier,
                    "raw_baseline_brier": result.raw_baseline_brier,
                    "raw_brier_skill": result.raw_brier_skill,
                    "n_obs": result.n_obs,
                    "base_rate": result.base_rate,
                }
            )

    written = _write_2x2_csv(rows, output_path)

    print()
    print(f"Wrote 2x2 summary to: {written}")
    print("2x2 results:")
    for row in rows:
        print(
            f"  q_sim={row['q_sim']}, q_link={row['q_link']}: "
            f"raw_brier={row['raw_brier']:.6f}, "
            f"raw_skill={row['raw_brier_skill']:.6f}"
        )


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    ran_anything = False

    if args.input is not None:
        if args.q_start is None or args.q_end is None or args.q_step is None:
            raise ValueError("Sweep mode requires --input, --q-start, --q-end, and --q-step")
        _run_sweep(args.input, args.q_start, args.q_end, args.q_step, args.output)
        ran_anything = True

    if args.input_q400 is not None or args.input_q850 is not None:
        if args.input_q400 is None or args.input_q850 is None:
            raise ValueError("2x2 mode requires both --input-q400 and --input-q850")
        _run_2x2(args.input_q400, args.input_q850, args.output_2x2)
        ran_anything = True

    if not ran_anything:
        raise ValueError(
            "Nothing to do. Provide either sweep arguments (--input, --q-start, --q-end, --q-step) "
            "and/or 2x2 arguments (--input-q400 and --input-q850)."
        )


if __name__ == "__main__":
    main()
