"""Published artifact declarations grouped behind the manifest artifact contract."""

from .banzuke import (
    BANZUKE_CHANGES_ARTIFACT,
    BANZUKE_DIVISION_BY_ERA_ARTIFACT,
    MAKUUCHI_RANK_BY_ERA_ARTIFACT,
)
from .standings import (
    STANDINGS_BY_WINS_ARTIFACT,
    BASHO_RESULTS_ARTIFACT,
)
from .career import (
    CAREER_LENGTH_ARTIFACT,
    LONGEST_CAREERS_ARTIFACT,
    RANK_AT_RETIREMENT_ARTIFACT,
    MOST_CONSECUTIVE_BOUTS_ARTIFACT,
    MOST_CAREER_WINS_ARTIFACT,
    MOST_CAREER_LOSSES_ARTIFACT,
    HIGHEST_EQUELO_ARTIFACT,
    FIRST_CHII_APPEARANCE_ARTIFACT,
    DIVISION_STABILITY_ARTIFACT,
)
from .ratings import (
    FINISH_BY_CHII_ARTIFACT,
    CAREER_COMPARISONS_ARTIFACT,
    TYPICAL_EQUELO_VALUES_ARTIFACT,
    WIN_PROBABILITY_BY_STANDING_ARTIFACT,
)

from .rating_changes import RATING_CHANGES_ARTIFACT
