# File written by .\table_parser.py. Do not edit!

from enum import Enum, auto
class Kimarite(Enum):
    UNCLASSIFIED = ''
    ABISETAOSHI = 'abisetaoshi'
    AMIUCHI = 'amiuchi'
    ASHITORI = 'ashitori'
    CHONGAKE = 'chongake'
    DASHINAGE = 'dashinage'
    FUMIDASHI = 'fumidashi'
    GASSHOHINERI = 'gasshohineri'
    HANSOKU = 'hansoku'
    HARIMANAGE = 'harimanage'
    HATAKIKOMI = 'hatakikomi'
    HIKIOTOSHI = 'hikiotoshi'
    HIKKAKE = 'hikkake'
    IPPONZEOI = 'ipponzeoi'
    ISAMIASHI = 'isamiashi'
    IZORI = 'izori'
    KAINAHINERI = 'kainahineri'
    KAKENAGE = 'kakenage'
    KATASUKASHI = 'katasukashi'
    KAWAZUGAKE = 'kawazugake'
    KEKAESHI = 'kekaeshi'
    KETAGURI = 'ketaguri'
    KIMEDASHI = 'kimedashi'
    KIMETAOSHI = 'kimetaoshi'
    KIRIKAESHI = 'kirikaeshi'
    KOMATASUKUI = 'komatasukui'
    KOSHIKUDAKE = 'koshikudake'
    KOSHINAGE = 'koshinage'
    KOTEHINERI = 'kotehineri'
    KOTENAGE = 'kotenage'
    KOZUMATORI = 'kozumatori'
    KUBIHINERI = 'kubihineri'
    KUBINAGE = 'kubinage'
    MAKIOTOSHI = 'makiotoshi'
    MITOKOROZEME = 'mitokorozeme'
    NICHONAGE = 'nichonage'
    NIMAIGERI = 'nimaigeri'
    OKURIDASHI = 'okuridashi'
    OKURIHIKIOTOSHI = 'okurihikiotoshi'
    OKURINAGE = 'okurinage'
    OKURITAOSHI = 'okuritaoshi'
    OKURITSURIDASHI = 'okuritsuridashi'
    OKURITSURIOTOSHI = 'okuritsuriotoshi'
    OMATA = 'omata'
    OSAKATE = 'osakate'
    OSHIDASHI = 'oshidashi'
    OSHITAOSHI = 'oshitaoshi'
    SABAORI = 'sabaori'
    SAKATOTTARI = 'sakatottari'
    SHITATEDASHINAGE = 'shitatedashinage'
    SHITATEHINERI = 'shitatehineri'
    SHITATENAGE = 'shitatenage'
    SOKUBIOTOSHI = 'sokubiotoshi'
    SOTOGAKE = 'sotogake'
    SOTOKOMATA = 'sotokomata'
    SOTOMUSO = 'sotomuso'
    SUKUINAGE = 'sukuinage'
    SUSOHARAI = 'susoharai'
    SUSOTORI = 'susotori'
    TASUKIZORI = 'tasukizori'
    TOKKURINAGE = 'tokkurinage'
    TOTTARI = 'tottari'
    TSUKAMINAGE = 'tsukaminage'
    TSUKIDASHI = 'tsukidashi'
    TSUKIHIZA = 'tsukihiza'
    TSUKIOTOSHI = 'tsukiotoshi'
    TSUKITAOSHI = 'tsukitaoshi'
    TSUKITE = 'tsukite'
    TSUMATORI = 'tsumatori'
    TSURIDASHI = 'tsuridashi'
    TSURIOTOSHI = 'tsuriotoshi'
    TSUTAEZORI = 'tsutaezori'
    UCHIGAKE = 'uchigake'
    UCHIMUSO = 'uchimuso'
    USHIROMOTARE = 'ushiromotare'
    UTCHARI = 'utchari'
    UWATEDASHINAGE = 'uwatedashinage'
    UWATEHINERI = 'uwatehineri'
    UWATENAGE = 'uwatenage'
    WARIDASHI = 'waridashi'
    WATASHIKOMI = 'watashikomi'
    YAGURANAGE = 'yaguranage'
    YOBIKAESHI = 'yobikaeshi'
    YOBIMODOSHI = 'yobimodoshi'
    YORIKIRI = 'yorikiri'
    YORITAOSHI = 'yoritaoshi'
    ZUBUNERI = 'zubuneri'

    @classmethod
    def from_string(cls, value: str) -> 'Kimarite':
        """Convert string to Kimarite enum value"""
        try:
            # Try to find by value
            for k in cls:
                if k.value == value:
                    return k
            # If not found, return UNCLASSIFIED
            return cls.UNCLASSIFIED
        except (ValueError, KeyError):
            return cls.UNCLASSIFIED
